<?php
require_once '../includes/auth.php';
require_once '../includes/config.php';

header('Content-Type: application/json');

// Only admins can access this
if (!isset($_SESSION['role']) || $_SESSION['role'] !== 'admin') {
    echo json_encode(['success' => false, 'message' => 'Unauthorized']);
    exit;
}

$action = $_REQUEST['action'] ?? '';

if ($action === 'fetch_cashiers') {
    try {
        $stmt = $pdo->query("SELECT id, emp_id, full_name, username, created_at FROM users WHERE role = 'cashier' ORDER BY created_at DESC");
        $cashiers = $stmt->fetchAll(PDO::FETCH_ASSOC);
        echo json_encode(['success' => true, 'cashiers' => $cashiers]);
    } catch (PDOException $e) {
        echo json_encode(['success' => false, 'message' => 'DB Error']);
    }
    exit;
}

if ($action === 'add_cashier') {
    $fullName = trim($_POST['full_name']);
    $username = trim($_POST['username']);
    $password = $_POST['password'];

    if (empty($fullName) || empty($username) || empty($password)) {
        echo json_encode(['success' => false, 'message' => 'All fields are required']);
        exit;
    }

    // Check if username exists
    $stmt = $pdo->prepare("SELECT id FROM users WHERE username = ?");
    $stmt->execute([$username]);
    if ($stmt->fetch()) {
        echo json_encode(['success' => false, 'message' => 'Username already taken']);
        exit;
    }

    $hashedPassword = password_hash($password, PASSWORD_DEFAULT);

    try {
        // emp_id is generated by DB trigger
        $stmt = $pdo->prepare("INSERT INTO users (full_name, username, password, role) VALUES (?, ?, ?, 'cashier')");
        if ($stmt->execute([$fullName, $username, $hashedPassword])) {
            echo json_encode(['success' => true]);
        } else {
            echo json_encode(['success' => false, 'message' => 'Failed to add cashier']);
        }
    } catch (PDOException $e) {
        echo json_encode(['success' => false, 'message' => 'Database error: ' . $e->getMessage()]);
    }
    exit;
}

if ($action === 'delete_cashier') {
    $id = $_POST['id'];
    
    // Prevent deleting self (though role check handles this, good to be safe if reused)
    if ($id == $_SESSION['id']) {
        echo json_encode(['success' => false, 'message' => 'Cannot delete yourself']);
        exit;
    }

    try {
        $stmt = $pdo->prepare("DELETE FROM users WHERE id = ? AND role = 'cashier'");
        if ($stmt->execute([$id])) {
            echo json_encode(['success' => true]);
        } else {
            echo json_encode(['success' => false, 'message' => 'Failed to delete cashier']);
        }
    } catch (PDOException $e) {
        // Likely foreign key constraint if they have sales history
        // In that case, we might want to soft delete, but for now strict delete or error is fine
        echo json_encode(['success' => false, 'message' => 'Cannot delete cashier with active history. Deactivate instead? (Feature pending)']);
    }
    exit;
}
